{% set name = "metamdbg" %}
{% set version = "1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/GaetanBenoitDev/metaMDBG/archive/refs/tags/metaMDBG-{{ version }}.tar.gz
  sha256: e482a1a5898634ca2c2712943606b0b3c98e6623709f097791e8b96ae26601a0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('metamdbg', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - zlib
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - libgomp # [linux]
    - llvm-openmp  # [osx]
    - minimap2 =2.28
    - time =1.8

test:
  commands:
    - metaMDBG 2>&1 | grep 'Usage'

about:
  home: "https://github.com/GaetanBenoitDev/metaMDBG"
  license: MIT
  license_family: MIT
  license_file: "LICENSE.md"
  summary: 'MetaMDBG: a lightweight assembler for long and accurate metagenomics reads.'
  dev_url: "https://github.com/GaetanBenoitDev/metaMDBG"
  doc_url: "https://github.com/GaetanBenoitDev/metaMDBG/blob/metaMDBG-{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1038/s41587-023-01983-6
